# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYVXlv7KvC5nmXW8I_iGpBz0nj95LGBI
"""

import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("anxiety_depression_data.csv")

print("--- PRIMEIRAS LINHAS DO ARQUIVO ---")

print(df.head())

df["High_Anxiety"] = (df["Anxiety_Score"] >= 7).astype(int)

print("Contagem de casos")

print(df["High_Anxiety"].value_counts())

df["High_Anxiety"].value_counts().plot(kind="bar")

plt.title("Ansiedade Alta vs Baixa")

plt.show()

df = df.drop("Anxiety_Score", axis=1)

df = pd.get_dummies(df)

X = df.drop("High_Anxiety", axis=1)

y = df["High_Anxiety"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

modelo = RandomForestClassifier()

modelo.fit(X_train, y_train)

pred = modelo.predict(X_test)

print("Resultados modelo original")

print("Acurácia:", accuracy_score(y_test, pred))

print("Matriz de confusão", confusion_matrix(y_test, pred))

print("rodando experimentos")

modelo1 = RandomForestClassifier(n_estimators=200)

modelo1.fit(X_train, y_train)

pred1 = modelo1.predict(X_test)

print("Experimento 1(Mais árvores):", accuracy_score(y_test, pred1))

modelo2 = RandomForestClassifier(max_depth=5)

modelo2.fit(X_train, y_train)

pred2 = modelo2.predict(X_test)

print("Experimento 2 (àrvore limitada):", accuracy_score(y_test, pred2))

X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2, random_state=42)

modelo3 = RandomForestClassifier()

modelo3.fit(X_train2, y_train2)

pred3 = modelo3.predict(X_test2)

print("Experimento 3 (Divisão 80/20):", accuracy_score(y_test2, pred3))